dist: xenial
sudo: false

language: go

go:
  - 1.13

services:
  - postgresql

addons:
  postgresql: "9.5"

install:
  - go get github.com/onsi/ginkgo/ginkgo

script:
  - export APP_ROOT="$TRAVIS_BUILD_DIR"
  - ginkgo -r -nodes=4
